DataFile            time_ser_ALES40.mom
DataDirectory         ./obs_files
interpolate           no
OutputFile            ./pre_files/time_ser_ALES40.mom
seasonalsignal        yes
halfseasonalsignal    yes
estimateoffsets       yes
estimatepostseismic   yes
estimateslowslipevent yes
ScaleFactor           1.0
PhysicalUnit          mm
IQ_factor             3
