DataFile            1670509522090575_series.mom
DataDirectory         ./obs_files
interpolate           no
OutputFile            ./pre_files/1670509522090575_series.mom
seasonalsignal        yes
halfseasonalsignal    yes
estimateoffsets       no
estimatepostseismic   no
estimateslowslipevent no
ScaleFactor           1.0
PhysicalUnit          mm
IQ_factor             3
